language: ruby
services:
  - redis
rvm:
  - 1.9.3
before_script:
  - ps ax
  - sudo service mysql stop
  - 'RAILS_ENV=test rake db:create db:schema:load --trace'
script:
  - './build.sh'
notifications:
  irc: "irc.freenode.org#travis"
after_failure: "sudo cat /var/log/redis/redis.log"
